api:
  interval: 5min
  url: https://api.twelvedata.com/time_series

data:
  start_date: "2024-01-01 00:00:00"
  end_date: "2024-07-01 00:00:00"
  test_start: "2024-01-01"
  test_end: "2024-07-01"

model:
  time_interval_train: 24
  prediction_interval: 288
  epochs: 10
  batch_size: 64